# name of our workflow
name: Django CI Workflow

# Triggers for our workflow
on:
  # opening a pull request to amster and develop-qa branch will be a trigger
  pull_request:
    branches:
      - devops-qa
      - main
  # any code pushed to master and devops branch will also be a trigger
  push:
    branches:
      - main
      - devops-qa

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Link with Flake8
        run: |
          flake8 .
      - name: run Tests
        run: |
          python foodvault/manage.py test
